services:
  backend:
    image: "ghcr.io/dhbw-meow/eduflow-backend:latest"
    environment:
      - RUST_LOG=INFO
    ports:
      - "3000:3000"
    volumes:
      - app_data:/app/data


volumes:
  app_data: