services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped

    ports:
      - 80:80
      - 443:443

    env_file:
      - ./.env

    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro

  backend:
    image: "ghcr.io/dhbw-meow/eduflow-backend:latest"
    container_name: backend
    restart: unless-stopped

    environment:
      - RUST_LOG=INFO
      - FRONTEND_CORS_URL=${FRONTEND_CORS_URL}
    
    volumes:
      - app_data:/app/data

  frontend:
    image: "ghcr.io/dhbw-meow/eduflow-frontend:latest"
    container_name: frontend
    restart: unless-stopped
    depends_on:
      - backend

    env_file:
      - ./.env

    post_start:
      - command: ["sh", "-c", "/generate_endpoint_data.sh"]

    volumes:
      - ./api_endpoint_template.txt:/usr/share/nginx/html/api_endpoint_template.txt
      - ./generate_endpoint_data.sh:/generate_endpoint_data.sh

volumes:
  app_data: